### ISSUE TITLE
[BUG]  The workflow is not matching the collection by _postman_id, so only creates rather than updates a collection

### ISSUE THREAD

**Issue by geoff-maddock** [jneate/postman-collection-action#216]
**Describe the bug**
I implemented this action as a dispatchable workflow, configured and tested it.  It successfully created a collection in my postman workspace that's specified by the workspace_id.   However, the collection created does not have a postman_id that matches the info._postman_id value that's specified in the collection.json.   Also, if I run the workflow again, it does not update the collection, but instead creates another duplicate with a different postman_id.

**To Reproduce**
Since this is in a private repo, I can't give access, but a cleaned version of the json:
```
{
	"info": {
		"_postman_id": "2748bf95-0614-4f10-b041-d2362accbddb",
		"name": "hopper",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
		"_exporter_id": "196575"
	},
	"item": [
		{
			"name": "cancel notice",
			"item": [
				{
					"name": "Get Cancel Notices",
					"event": [
						{
							"listen": "test",
							"script": {
								"exec": [
									"pm.test(\"Status code is 200\", function () {\r",
									"    pm.response.to.have.status(200);\r",
									"});\r",
									"\r",
									"var jsonData = pm.response.json();\r",
									"\r",
									"pm.test(\"Ensure response has data\", function () {\r",
									"    pm.expect(jsonData.data.length).to.not.eql(0);\r",
									"});\r",
									"pm.test(\"Ensure response has a total greater than 1\", function () {\r",
									"    pm.expect(jsonData.total).to.be.above(1);\r",
									"});\r",
									"\r",
									"pm.test(\"Ensure response includes all keys\", function () {\r",
									"    pm.expect(jsonData.data[0]).to.have.all.keys(\r",
									"        'id', \r",
									"        'created_at',\r",
									"        'updated_at',\r",
									"        'name',\r",
									"        'number_of_days',\r",
									"        'number_of_months',\r",
									"        'is_active',\r",
									"        );\r",
									"});\r",
									"\r",
									"pm.test(\"Ensure response values are valid types\", function () {\r",
									"    pm.expect(jsonData.data[0].id).to.be.a(\"Number\");\r",
									"    pm.expect(jsonData.data[0].created_at).to.be.a(\"String\");\r",
									"    pm.expect(jsonData.data[0].updated_at).to.be.a(\"String\");\r",
									"    pm.expect(jsonData.data[0].name).to.be.a(\"String\");\r",
									"    pm.expect(jsonData.data[0].number_of_days).to.be.a(\"Number\");\r",
									"    pm.expect(jsonData.data[0].number_of_months).to.be.a(\"Number\");\r",
									"    pm.expect(jsonData.data[0].is_active).to.be.a(\"boolean\");\r",
									"});\r",
									"\r",
									"pm.environment.set(\"cancelNoticeId\", jsonData.data[0].id);\r",
									""
								],
								"type": "text/javascript"
							}
						}
					],
					"request": {
						"method": "GET",
						"header": [
							{
								"key": "Auth-Username",
								"value": "{{Auth-Username}}",
								"type": "text"
							}
						],
						"url": {
							"raw": "{{baseUrl}}/cancel-notices",
							"host": [
								"{{baseUrl}}"
							],
							"path": [
								"cancel-notices"
							]
						}
					},
					"response": []
				},
		{
			"name": "Get Docs",
			"event": [
				{
					"listen": "test",
					"script": {
						"exec": [
							"pm.test(\"Status code is 200\", function () {\r",
							"    pm.response.to.have.status(200);\r",
							"});\r",
							""
						],
						"type": "text/javascript"
					}
				}
			],
			"request": {
				"method": "GET",
				"header": [
					{
						"key": "exampleId",
						"value": "1",
						"type": "text"
					}
				],
				"url": {
					"raw": "{{baseUrl}}/docs",
					"host": [
						"{{baseUrl}}"
					],
					"path": [
						"docs"
					]
				}
			},
			"response": []
		}
	],
	"auth": {
		"type": "basic",
		"basic": [
			{
				"key": "password",
				"value": "{{password}}",
				"type": "string"
			},
			{
				"key": "username",
				"value": "{{username}}",
				"type": "string"
			}
		]
	},
	"event": [
		{
			"listen": "prerequest",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		},
		{
			"listen": "test",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		}
	]
}
```

**Expected behavior**
I would expect the workflow to use the info._postman_id, to replace the collection in our workspace

**Screenshots**
n/a

**Action Version**
jneate/postman-collection-action@v1

**Additional context**

Here's the whole of the workflow that my dispatchable workflow calls:
```
name: Sync Postman Collection
on: 
  workflow_call:
    inputs:
      POSTMAN_WORKSPACE_ID:
        required: true
        description: 'The ID of the Postman workspace to sync to'
        type: string
    secrets:
      POSTMAN_API_KEY:
        required: true
jobs:
  syncPostmanCollection:
    name: Sync Postman Collection
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Sync
      uses: jneate/postman-collection-action@v1
      with:
        postmanApiKey: ${{ secrets.POSTMAN_API_KEY }}
        postmanWorkspaceId: ${{ inputs.POSTMAN_WORKSPACE_ID }}
        postmanTimeout: 30000
```
